broker-url: http://localhost:3000

publish:
  type: provider
  path: ./data_test/api-spec.json
  name: user_service

update-deployment:
  name: user_service

test:
  name: user_service
  provider-url: http://localhost:3002

deploy-guard:
  name: user_service