broker-url: http://localhost:3000

publish:
  type: consumer
  path: ./contracts/cons-prov.json
  name: service_1

update-deployment:
  name: user_service

test:
  name: user_service
  provider-url: http://localhost:3002

deploy-guard:
  name: user_service

proxy:
  path: ./contracts/cons-prov.json
  port: 3004
  target: http://localhost:3002
  name: service_1
  provider-name: user_service

register-env:
  environment: production